data_parameters:
  datasets_path: dbfs:/mnt/dbacademy-datasets/generative-ai-solution-development/v01/arxiv-articles/
  catalog_name: hemzai
  bronze_schema_name: bronze
  silver_schema_name: silver
  gold_schema_name: gold
  pdf_raw_table_name: pdf_raw_text
  pdf_chunk_table_name: pdf_text_chunks
  pdf_embeddings_table_name: pdf_text_embeddings
  vector_search_endpoint_sub_name: pilot
  pdf_self_managed_vector_index_name : pdf_text_self_managed_vs_index
  pdf_managed_vector_index_name : pdf_text_managed_vs_index
  chain_model_name: hemz-pilot-chain